# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mock-sensor"
BBFILE_PATTERN_meta-mock-sensor = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mock-sensor = "6"

LAYERDEPENDS_meta-mock-sensor = "core"
LAYERSERIES_COMPAT_meta-mock-sensor = "walnascar"
